---
fixtures:
  repositories:
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    simpcat: https://github.com/simp/pupmod-simp-simpcat
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    pam: "#{source_dir}"
